### ISSUE TITLE
Windows Defender detected virus in windows zip.

### ISSUE THREAD

**Issue by MrLinford** [Proopai/eve-o-preview#5]
When downloading the Windows 6.0.1.3.zip virus is detected.

![image](https://github.com/user-attachments/assets/b279a890-4fab-4971-bdc6-e8105b581796)

![image](https://github.com/user-attachments/assets/e6827a3f-f046-4d90-ae0a-370daa94eb00)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503

**Comment by Proopai** [comment]
Yeah I am not sure why this is happening most likely it has to do with the fact of how the application hooks into the DLL's to pull the window information out and into its own Preview. 

This is a 100% false Positive and I am investigating how to get this fixed.  It could also be due to the version of .net that is being used.

Feel free to look at all the code its in this repo there is no viruses in it.  But like I said I am indeed looking to fix this.

**Comment by Proopai** [comment]
Also the exe has been submitted to Microsoft to verify along with all the source code with it to be able to get it flagged not infected I will update when they get back to me.

**Comment by Proopai** [comment]
![image](https://github.com/user-attachments/assets/255aed46-a3de-4cce-b2fe-1975196f70de)

**Comment by Proopai** [comment]
Confirmed by Windows that this is not a issue and a False Positive

![image](https://github.com/user-attachments/assets/d2d6a13c-07a2-49d8-911a-1370ddf6f7bd)
